AWSTemplateFormatVersion: 2010-09-09
Description: 'Test frontend instance'

#################################################################################
### Conditions
#################################################################################
Conditions:
  InUsEast1: !Equals
    - !Ref 'AWS::Region'
    - us-east-1

#################################################################################
### Parameters
#################################################################################
Parameters:

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  AglWebInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
    Description: Web EC2 instance type

  AglAppInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
    Description: App EC2 instance type

  AglInstanceKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Default: vockey

#################################################################################
### Resources
#################################################################################
Resources:

  TestEC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: true
          SubnetId: !ImportValue AglPubNet1Id
          GroupSet:
            - !ImportValue AglWebSgId
      SourceDestCheck: false
      Tags:
        - Key: Name
          Value: TestEC2
      KeyName: vockey                
      UserData:
        Fn::Base64:
          !Sub 
            - |
              #!/bin/bash
              yum -y update
              yum -y install httpd python3-pip

              # web service
              systemctl enable httpd
              systemctl start httpd

              # setup web environment
              find /var/www -type d -exec chmod 2775 {} \;
              find /var/www -type f -exec chmod 0664 {} \;
              usermod -a -G apache ec2-user
              chown -R ec2-user:apache /var/www
              chmod 2775 /var/www

              # install python packages
              su - ec2-user -c 'pip3 install flask flask-cors requests'
              su - ec2-user -c 'pip3 uninstall urllib3'
              su - ec2-user -c 'pip3 install "urllib3<2"'
              sleep 3

              # create config.py for backend params
              cat <<EOF > /home/ec2-user/config.py
              backend_url='http://${backendLbDNS}:8080/api/value'
              EOF
              sleep 3

              # download html, frontend.py
              su - ec2-user -c 'curl -o /var/www/html/index.html https://raw.githubusercontent.com/sushenghua/IS735/refs/heads/main/v2/front_index.html'
              su - ec2-user -c 'curl -o /home/ec2-user/frontend.py https://raw.githubusercontent.com/sushenghua/IS735/refs/heads/main/v2/frontend.py'

              # run frontend service script
              chown -R ec2-user:apache /home/ec2-user/*.py
              chmod 755 /home/ec2-user/*.py
              su - ec2-user -c 'python3 /home/ec2-user/frontend.py &'
            - backendLbDNS: !ImportValue AglVpcId

